/**
 * EDITOR PAGE ARCHITECTURE & CONCURRENT EXPORT GUIDE
 * ==================================================
 * 
 * OVERVIEW:
 * This page is the core of the AI Clip Editor. It allows users to preview the exact 
 * mathematical crop boundaries generated by the AI without decoding video frames, 
 * and export multiple clips concurrently via an async polling architecture.
 * 
 * --------------------------------------------------
 * 
 * THE CONCURRENT EXPORT SYSTEM (Step-by-Step):
 * 
 * Problem: Video rendering via FFmpeg takes time. If we blocked the HTTP request 
 * until FFmpeg finished, the browser would timeout. Furthermore, if a user wanted 
 * to export 3 different clips at the same time, a blocking modal would ruin the UX.
 * 
 * Solution: An asynchronous polling architecture managed by React state.
 * 
 * STEP 1: Dictionary State Management
 * Instead of `const [exportJob, setExportJob]`, we use a dictionary: 
 * `const [exportJobs, setExportJobs] = useState({})`. 
 * This allows O(1) lookups and infinite concurrent jobs (e.g. { 'job1': {...}, 'job2': {...} }).
 * 
 * STEP 2: The Initial Request (handleExport)
 * When the user clicks "Export Clip":
 *   1. We instantly generate a `tempId` and push a "queued" job to the state.
 *      This immediately shows a Toast Notification to the user so they know it started.
 *   2. We send a `POST /api/v1/export/process` request containing the clip boundaries.
 *   3. The backend spins off a background thread and returns a real `export_id`.
 *   4. We swap the `tempId` in our state dictionary for the real `export_id`.
 * 
 * STEP 3: The Global Polling Effect (useEffect)
 * To avoid creating a separate `setInterval` for every single export (which could 
 * crash the browser or cause memory leaks), we use a SINGLE Global Polling Loop.
 *   1. Every 2 seconds, the loop wakes up.
 *   2. It filters the `exportJobs` dictionary for any job with status === 'processing'.
 *   3. If it finds any, it fires off parallel `fetch()` requests to `GET /status/{id}`.
 *   4. It uses a `useRef(exportJobs)` to guarantee it always reads the freshest state 
 *      inside the interval closure without needing to constantly destroy/recreate the interval.
 * 
 * STEP 4: The Floating Toast UI
 * The UI iterates over `Object.values(exportJobs)` and renders a stack of floating 
 * glassmorphism cards in the bottom-right corner. Each card independently reads its 
 * status (queued, processing, completed, error) and animates its progress bar.
 * 
 * STEP 5: The Download Trigger
 * When the polling loop sees status === 'completed', it:
 *   1. Updates the toast UI to green ("Done").
 *   2. Triggers a hidden browser download via `window.location.href = /download/{id}`.
 *   3. Sets a 5-second `setTimeout` to automatically delete the job from the dictionary, 
 *      making the toast gracefully vanish.
 */
import React, { useState, useRef, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getFullVideoUrl } from '../services/videoApi';

export default function EditorPage() {
  const { savedFilename } = useParams();
  const navigate = useNavigate();
  const videoRef = useRef(null);
  
  const [isLoading, setIsLoading] = useState(true);
  const [videoError, setVideoError] = useState(false);
  
  const [activeClipId, setActiveClipId] = useState(null);
  const [clips, setClips] = useState([]);
  
  const activeClip = clips.find(c => c.id === activeClipId) || clips[0];

  // Add Custom Clip Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalTitle, setModalTitle] = useState('');
  const [modalStartTime, setModalStartTime] = useState(0);
  const [modalEndTime, setModalEndTime] = useState(30);
  const [modalText, setModalText] = useState('');

  // Timeline Drag-to-Scroll State
  const timelineRef = useRef(null);
  const [isDragging, setIsDragging] = useState(false);
  const [startX, setStartX] = useState(0);
  const [scrollLeft, setScrollLeft] = useState(0);
  const [hasDragged, setHasDragged] = useState(false);

  // For the Zero-CPU Preview overlay box
  const [boxPosition, setBoxPosition] = useState({ x: 50, y: 50 }); // percentage
  const [trackingData, setTrackingData] = useState([]);
  const [videoWidth, setVideoWidth] = useState(1920);
  const [videoHeight, setVideoHeight] = useState(1080);
  const [videoDuration, setVideoDuration] = useState(300);
  const [currentVideoTime, setCurrentVideoTime] = useState(0);

  // Export State (Dictionary to support multiple concurrent exports)
  const [exportJobs, setExportJobs] = useState({});
  const exportJobsRef = useRef(exportJobs);
  
  // Keep ref in sync for the interval
  useEffect(() => {
    exportJobsRef.current = exportJobs;
  }, [exportJobs]);

  // Fetch the real AI tracking data and clips from the backend
  useEffect(() => {
    async function fetchRecipe() {
      try {
        const response = await fetch(`http://localhost:8000/api/v1/pipeline/recipe/${encodeURIComponent(savedFilename)}`);
        if (response.status === 404) {
          // Video hasn't been processed yet, redirect to pipeline page
          navigate(`/pipeline/${savedFilename}`);
          return;
        }
        
        if (!response.ok) {
          throw new Error('Failed to fetch recipe');
        }
        
        const data = await response.json();
        
        if (data.global_tracking) {
          setTrackingData(data.global_tracking);
        }
        
        if (data.extracted_clips && data.extracted_clips.length > 0) {
          // Format clips to match React state schema
          const formattedClips = data.extracted_clips.map((c, i) => ({
            id: c.clip_id || `clip_${i}`,
            start_time: c.start_time_seconds,
            end_time: c.end_time_seconds,
            title: c.extraction_reasoning || `Clip ${i+1}`,
            text: c.text_transcript || "No transcript available"
          }));
          setClips(formattedClips);
          setActiveClipId(formattedClips[0].id);
        } else {
          // Fallback if no clips found but tracking exists
          const defaultClip = { id: 'clip_1', start_time: 0, end_time: 30, text: "Default clip", title: "Clip 1" };
          setClips([defaultClip]);
          setActiveClipId('clip_1');
        }
        
        setIsLoading(false);
      } catch (err) {
        console.error("Error fetching recipe:", err);
        setIsLoading(false);
      }
    }
    
    fetchRecipe();
  }, [savedFilename, navigate]);

  // Global Polling Effect for all active Export Jobs
  useEffect(() => {
    const intervalId = setInterval(async () => {
      const currentJobs = exportJobsRef.current;
      const processingJobs = Object.values(currentJobs).filter(j => j.status === 'processing');
      
      if (processingJobs.length === 0) return;
      
      for (const job of processingJobs) {
        if (job.id.startsWith('temp_')) continue;
        
        try {
          const res = await fetch(`http://localhost:8000/api/v1/export/status/${job.id}`);
          const data = await res.json();
          
          if (data.status === 'completed') {
            setExportJobs(prev => ({ ...prev, [job.id]: { ...prev[job.id], status: 'completed' } }));
            // Trigger actual file download
            window.location.href = `http://localhost:8000/api/v1/export/download/${job.id}`;
            
            // Auto remove toast after 5 seconds
            setTimeout(() => {
              setExportJobs(prev => {
                const newJobs = { ...prev };
                delete newJobs[job.id];
                return newJobs;
              });
            }, 5000);
          } else if (data.status === 'error') {
            setExportJobs(prev => ({ ...prev, [job.id]: { ...prev[job.id], status: 'error', error: data.error_detail } }));
          } else if (data.status === 'cancelled') {
            setExportJobs(prev => ({ ...prev, [job.id]: { ...prev[job.id], status: 'cancelled' } }));
          }
        } catch (e) {
          console.error(`Polling error for ${job.id}`, e);
        }
      }
    }, 2000);
    
    return () => clearInterval(intervalId);
  }, []);

  const handleTimelineMouseDown = (e) => {
    setIsDragging(true);
    setHasDragged(false);
    setStartX(e.pageX - timelineRef.current.offsetLeft);
    setScrollLeft(timelineRef.current.scrollLeft);
  };

  const handleTimelineMouseMove = (e) => {
    if (!isDragging) return;
    e.preventDefault();
    const x = e.pageX - timelineRef.current.offsetLeft;
    const walk = (x - startX) * 1.5; // Scroll speed multiplier
    if (Math.abs(walk) > 5) setHasDragged(true); // Treat as a drag, not a click
    timelineRef.current.scrollLeft = scrollLeft - walk;
  };

  const handleTimelineClick = (e, videoDur) => {
    if (hasDragged) return; // Prevent seeking if the user was just trying to scroll
    const rect = e.currentTarget.getBoundingClientRect();
    const percentage = (e.clientX - rect.left) / rect.width;
    if (videoRef.current) videoRef.current.currentTime = Math.max(0, Math.min(videoDur, percentage * videoDur));
  };

  const handleTimeUpdate = () => {
    if (!videoRef.current) return;
    const currentTime = videoRef.current.currentTime;
    setCurrentVideoTime(currentTime);
    
    if (trackingData.length === 0) return;
    
    // Find the active tracking block for this timestamp
    const currentBlock = trackingData.find(b => currentTime >= b.start_time_seconds && currentTime <= b.end_time_seconds);
    
    if (currentBlock) {
      if (currentBlock.crop_x !== undefined) {
        // Option 1: Backend provides exact FFmpeg crop coordinates (Source of Truth)
        let pX = (currentBlock.crop_x / videoWidth) * 100;
        let pY = (currentBlock.crop_y / videoHeight) * 100;
        setBoxPosition({ x: pX, y: pY });
      } else {
        // Option 2: Legacy fallback. Calculate the clamp math identically to how FFmpeg would do it.
        const crop_width = videoHeight * (9/16);
        const target_x = currentBlock.center_x_coordinate - (crop_width / 2);
        const clamped_x = Math.max(0, Math.min(videoWidth - crop_width, target_x));
        
        let pX = (clamped_x / videoWidth) * 100;
        setBoxPosition({ x: pX, y: 0 });
      }
    }
  };

  const handleLoadedMetadata = () => {
    if (videoRef.current) {
      setVideoDuration(videoRef.current.duration);
      if (videoRef.current.videoWidth) setVideoWidth(videoRef.current.videoWidth);
      if (videoRef.current.videoHeight) setVideoHeight(videoRef.current.videoHeight);
    }
  };

  const handleNumberChange = (val, field) => {
    let num = parseFloat(val);
    if (isNaN(num)) num = 0;
    setClips(clips.map(c => c.id === activeClipId ? { ...c, [field]: num } : c));
    
    // Seek video to the new time so user can preview their cut
    if (videoRef.current) {
      videoRef.current.currentTime = num;
    }
  };

  const handleTextChange = (val, field) => {
    setClips(clips.map(c => c.id === activeClipId ? { ...c, [field]: val } : c));
  };

  const openAddClipModal = () => {
    const startSec = Math.floor(currentVideoTime * 10) / 10;
    const endSec = Math.floor(Math.min(currentVideoTime + 30, videoDuration || currentVideoTime + 30) * 10) / 10;
    setModalTitle(`Custom Clip ${clips.length + 1}`);
    setModalStartTime(startSec);
    setModalEndTime(endSec);
    setModalText(`Custom clip from ${startSec}s to ${endSec}s`);
    setIsModalOpen(true);
  };

  const handleCreateClipFromModal = (e) => {
    e.preventDefault();
    const startNum = parseFloat(modalStartTime) || 0;
    const endNum = parseFloat(modalEndTime) || startNum + 5;
    
    const newClipId = `clip_${Date.now()}`;
    const newClip = {
      id: newClipId,
      start_time: Math.max(0, startNum),
      end_time: Math.min(videoDuration || endNum, Math.max(startNum + 0.5, endNum)),
      title: modalTitle || `Custom Clip ${clips.length + 1}`,
      text: modalText || "User created custom clip."
    };

    setClips(prev => [...prev, newClip]);
    setActiveClipId(newClipId);
    setIsModalOpen(false);

    if (videoRef.current) {
      videoRef.current.currentTime = newClip.start_time;
    }
  };

  const handleDeleteClip = (clipIdToDelete) => {
    if (clips.length <= 1) {
      alert("At least one clip must remain in the project.");
      return;
    }

    const updatedClips = clips.filter(c => c.id !== clipIdToDelete);
    setClips(updatedClips);

    if (activeClipId === clipIdToDelete) {
      setActiveClipId(updatedClips[0].id);
    }
  };

  const handleExport = async (clipToExport) => {
    const tempId = `temp_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    
    setExportJobs(prev => ({
      ...prev,
      [tempId]: { id: tempId, title: clipToExport.title, status: 'queued', isExporting: true }
    }));
    
    try {
      const payload = {
        saved_filename: savedFilename || 'demo.mp4',
        start_time: clipToExport.start_time,
        end_time: clipToExport.end_time,
        tracking_data: trackingData
      };

      const response = await fetch('http://localhost:8000/api/v1/export/process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      
      const data = await response.json();
      
      if (!response.ok) {
        throw new Error(data.detail || "Failed to start export");
      }
      
      if (data.status === 'already_running') {
        // Swap temp ID for the real ID that is already running
        setExportJobs(prev => {
          const newJobs = { ...prev };
          delete newJobs[tempId];
          newJobs[data.export_id] = { id: data.export_id, title: clipToExport.title, status: 'processing', isExporting: true };
          return newJobs;
        });
        return;
      }

      // Set the real export ID to start the polling effect
      setExportJobs(prev => {
        const newJobs = { ...prev };
        delete newJobs[tempId];
        newJobs[data.export_id] = { id: data.export_id, title: clipToExport.title, status: 'processing', isExporting: true };
        return newJobs;
      });
      
    } catch (error) {
      setExportJobs(prev => ({
        ...prev,
        [tempId]: { ...prev[tempId], status: 'error', error: error.message }
      }));
    }
  };

  const handleExportAll = () => {
    clips.forEach(clip => {
      handleExport(clip);
    });
  };

  const handleCancelExport = async (exportId) => {
    // If it's still a temporary ID, it hasn't even reached the server yet. Just remove it locally.
    if (exportId.startsWith('temp_')) {
      setExportJobs(prev => {
        const newJobs = { ...prev };
        delete newJobs[exportId];
        return newJobs;
      });
      return;
    }
    
    // Optimistically mark as cancelling
    setExportJobs(prev => ({ ...prev, [exportId]: { ...prev[exportId], status: 'cancelling' } }));
    
    try {
      const res = await fetch(`http://localhost:8000/api/v1/export/cancel/${exportId}`, { method: 'POST' });
      
      if (res.ok) {
        alert("Export cancelled successfully! Server CPU has been freed.");
      } else {
        const errData = await res.json();
        alert(`Warning: Failed to cancel export. Server said: ${errData.detail}`);
      }
      // The polling loop will ultimately catch the 'cancelled' status and update the UI
    } catch (err) {
      console.error("Failed to cancel export", err);
      alert("Failed to cancel export job due to network error.");
    }
  };

  if (isLoading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '60vh', flexDirection: 'column', gap: '1rem' }}>
        <style>{`
          @keyframes spin { 100% { transform: rotate(360deg); } }
        `}</style>
        <div style={{ width: '40px', height: '40px', border: '4px solid rgba(0, 255, 204, 0.3)', borderTop: '4px solid #00ffcc', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
        <h3 style={{ color: '#00ffcc' }}>Loading AI Tracking Data...</h3>
      </div>
    );
  }

  if (videoError) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '60vh', flexDirection: 'column', gap: '1rem' }}>
        <h2 style={{ color: '#ef4444' }}>⚠️ Video Not Found</h2>
        <p style={{ color: '#aaa', maxWidth: '400px', textAlign: 'center' }}>
          The video file could not be loaded from storage. It may have expired or been deleted.
        </p>
        <button className="btn-primary" onClick={() => navigate('/')} style={{ marginTop: '1rem' }}>
          Back to Home
        </button>
      </div>
    );
  }

  return (
    <div className="editor-page-root" style={{ padding: '2rem 3rem', minHeight: 'calc(100vh - 80px)', display: 'flex', flexDirection: 'column', boxSizing: 'border-box' }}>
      
      {/* Floating Export Toast Notifications */}
      {Object.keys(exportJobs).length > 0 && (
        <div style={{
          position: 'fixed',
          bottom: '20px',
          right: '20px',
          display: 'flex',
          flexDirection: 'column',
          gap: '10px',
          zIndex: 9999,
          maxWidth: '350px'
        }}>
          {Object.values(exportJobs).map(job => (
            <div key={job.id} className="glass-panel" style={{ padding: '1.2rem', display: 'flex', flexDirection: 'column', gap: '8px', border: `1px solid ${job.status === 'completed' ? '#10b981' : job.status === 'error' || job.status === 'cancelled' ? '#ef4444' : '#00ffcc'}`, borderLeftWidth: '4px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <strong style={{ color: '#fff', fontSize: '0.9rem' }}>{job.title}</strong>
                <span style={{ fontSize: '0.8rem', color: job.status === 'completed' ? '#10b981' : job.status === 'error' || job.status === 'cancelled' ? '#ef4444' : '#00ffcc' }}>
                  {job.status === 'completed' ? 'Done' : job.status === 'error' ? 'Failed' : job.status === 'cancelled' ? 'Cancelled' : job.status === 'cancelling' ? 'Cancelling...' : 'Exporting...'}
                </span>
              </div>
              
              {job.status === 'error' && (
                <div style={{ color: '#ef4444', fontSize: '0.8rem' }}>{job.error}</div>
              )}
              
              {(job.status === 'queued' || job.status === 'processing' || job.status === 'cancelling') && (
                <div style={{ width: '100%', height: '4px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', overflow: 'hidden' }}>
                  <div style={{ 
                    width: job.status === 'processing' ? '70%' : '20%', 
                    height: '100%', 
                    background: '#00ffcc', 
                    transition: 'width 0.5s ease',
                    animation: job.status === 'processing' ? 'pulse 2s infinite' : 'none' 
                  }} />
                </div>
              )}
              
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: '4px' }}>
                {(job.status === 'queued' || job.status === 'processing') && (
                  <button className="btn-secondary" style={{ padding: '4px 8px', fontSize: '0.8rem', border: '1px solid #ef4444', color: '#ef4444' }} onClick={() => handleCancelExport(job.id)}>
                    Cancel
                  </button>
                )}
                
                {(job.status === 'error' || job.status === 'completed' || job.status === 'cancelled') && (
                  <button className="btn-secondary" style={{ padding: '4px 8px', fontSize: '0.8rem' }} onClick={() => {
                    setExportJobs(prev => {
                      const newJobs = { ...prev };
                      delete newJobs[job.id];
                      return newJobs;
                    });
                  }}>Dismiss</button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Add Custom Clip Modal */}
      {isModalOpen && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(5, 8, 15, 0.85)',
          backdropFilter: 'blur(10px)',
          WebkitBackdropFilter: 'blur(10px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 10000,
          padding: '1rem'
        }}>
          <div className="glass-panel" style={{ width: '100%', maxWidth: '500px', padding: '2rem', border: '1px solid rgba(0, 255, 204, 0.4)', boxShadow: '0 0 30px rgba(0, 255, 204, 0.15)' }}>
            <h3 style={{ color: '#fff', marginTop: 0, marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ color: '#00ffcc' }}>🎬</span> Add New Custom Clip
            </h3>
            
            <form onSubmit={handleCreateClipFromModal} style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem' }}>
              <div>
                <label style={{ display: 'block', color: '#ccc', marginBottom: '0.4rem', fontSize: '0.9rem' }}>
                  Clip Title
                </label>
                <input 
                  type="text" 
                  required
                  value={modalTitle} 
                  onChange={(e) => setModalTitle(e.target.value)}
                  placeholder="e.g. Action Intro, Key Highlight"
                  style={{ width: '100%', padding: '0.75rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#fff', borderRadius: '8px', fontSize: '0.95rem', boxSizing: 'border-box' }} 
                />
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div>
                  <label style={{ display: 'block', color: '#ccc', marginBottom: '0.4rem', fontSize: '0.9rem' }}>
                    Start Time (s)
                  </label>
                  <input 
                    type="number" 
                    step="0.1"
                    min="0"
                    max={videoDuration}
                    required
                    value={modalStartTime} 
                    onChange={(e) => setModalStartTime(e.target.value)}
                    style={{ width: '100%', padding: '0.75rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#00ffcc', borderRadius: '8px', fontSize: '1rem', fontWeight: 'bold', boxSizing: 'border-box' }} 
                  />
                </div>
                
                <div>
                  <label style={{ display: 'block', color: '#ccc', marginBottom: '0.4rem', fontSize: '0.9rem' }}>
                    End Time (s)
                  </label>
                  <input 
                    type="number" 
                    step="0.1"
                    min="0"
                    max={videoDuration}
                    required
                    value={modalEndTime} 
                    onChange={(e) => setModalEndTime(e.target.value)}
                    style={{ width: '100%', padding: '0.75rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#00ffcc', borderRadius: '8px', fontSize: '1rem', fontWeight: 'bold', boxSizing: 'border-box' }} 
                  />
                </div>
              </div>

              <div>
                <label style={{ display: 'block', color: '#ccc', marginBottom: '0.4rem', fontSize: '0.9rem' }}>
                  Description / Notes
                </label>
                <textarea 
                  rows="3"
                  value={modalText} 
                  onChange={(e) => setModalText(e.target.value)}
                  placeholder="Notes or details about this custom clip..."
                  style={{ width: '100%', padding: '0.75rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#aaa', borderRadius: '8px', fontSize: '0.9rem', resize: 'vertical', boxSizing: 'border-box' }} 
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem', marginTop: '0.5rem' }}>
                <button 
                  type="button" 
                  className="btn-secondary" 
                  onClick={() => setIsModalOpen(false)}
                  style={{ padding: '0.6rem 1.2rem' }}
                >
                  Cancel
                </button>
                <button 
                  type="submit" 
                  className="btn-primary" 
                  style={{ padding: '0.6rem 1.4rem' }}
                >
                  Create Clip
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h2>Interactive Clip Editor <span style={{ color: '#00ffcc' }}>🎬</span></h2>
        <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
          <button className="btn-secondary" onClick={() => navigate('/')}>
            ⬅️ Back to Pipeline
          </button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 370px', gap: '2rem', flex: 1, minHeight: 0 }}>
        
        {/* LEFT COLUMN: Zero-CPU Preview Player */}
        <div className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', minHeight: 0, minWidth: 0 }}>
          <h3 style={{ color: '#00ffcc', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect></svg>
            Zero-CPU Tracking Preview
          </h3>
          
          <div style={{ position: 'relative', width: '100%', backgroundColor: '#050505', borderRadius: '12px', overflow: 'hidden', display: 'inline-block' }}>
            <video 
              ref={videoRef}
              src={getFullVideoUrl(`/storage/uploads/${encodeURIComponent(savedFilename)}`)}
              controls
              onError={() => setVideoError(true)}
              onTimeUpdate={handleTimeUpdate}
              onLoadedMetadata={handleLoadedMetadata}
              style={{ width: '100%', maxHeight: '60vh', display: 'block' }}
            />
            
            {/* The 9:16 tracking overlay box */}
            <div style={{
              position: 'absolute',
              top: 0,
              height: '100%',
              aspectRatio: '9 / 16',
              border: '3px solid #00ffcc',
              boxShadow: '0 0 0 9999px rgba(0,0,0,0.6), inset 0 0 15px rgba(0, 255, 204, 0.3)',
              left: `${boxPosition.x}%`,
              top: `${boxPosition.y}%`,
              pointerEvents: 'none',
              display: 'flex',
              flexDirection: 'column',
              padding: '10px'
            }}>
              <div style={{ background: 'rgba(0, 255, 204, 0.9)', color: '#000', fontSize: '0.7rem', padding: '2px 8px', borderRadius: '4px', alignSelf: 'flex-start', fontWeight: 'bold' }}>
                9:16 CROP AREA
              </div>
            </div>
          </div>
          
          {/* Scrollable Visual Timeline Bar */}
          <div 
            ref={timelineRef}
            className="custom-scrollbar" 
            style={{ 
              marginTop: '1.5rem', 
              width: '100%', 
              overflowX: 'auto', 
              borderRadius: '8px', 
              border: '1px solid rgba(255,255,255,0.1)', 
              background: 'rgba(0,0,0,0.5)', 
              paddingBottom: '4px',
              cursor: isDragging ? 'grabbing' : 'grab' 
            }}
            onMouseDown={handleTimelineMouseDown}
            onMouseMove={handleTimelineMouseMove}
            onMouseUp={() => setIsDragging(false)}
            onMouseLeave={() => setIsDragging(false)}
          >
            <div 
              style={{ width: `${Math.max(100, videoDuration * 4)}px`, minWidth: '100%', height: '54px', position: 'relative', flexShrink: 0 }}
              onClick={(e) => handleTimelineClick(e, videoDuration)}
            >
              {/* Render regions for ALL clips on the visual timeline */}
              {clips.map(clip => {
                const isActive = clip.id === activeClipId;
                const leftPct = (clip.start_time / videoDuration) * 100;
                const widthPct = ((clip.end_time - clip.start_time) / videoDuration) * 100;

                return (
                  <div 
                    key={clip.id}
                    onClick={(e) => {
                      e.stopPropagation();
                      setActiveClipId(clip.id);
                      if (videoRef.current) videoRef.current.currentTime = clip.start_time;
                    }}
                    style={{
                      position: 'absolute',
                      left: `${leftPct}%`,
                      width: `${widthPct}%`,
                      height: '100%',
                      background: isActive ? 'rgba(0, 255, 204, 0.35)' : 'rgba(168, 85, 247, 0.25)',
                      borderLeft: `2px solid ${isActive ? '#00ffcc' : '#c084fc'}`,
                      borderRight: `2px solid ${isActive ? '#00ffcc' : '#c084fc'}`,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      overflow: 'hidden',
                      zIndex: isActive ? 5 : 2,
                      transition: 'background 0.2s, border-color 0.2s'
                    }}
                    title={`${clip.title} (${clip.start_time.toFixed(1)}s - ${clip.end_time.toFixed(1)}s)`}
                  >
                    <span style={{ 
                      color: isActive ? '#00ffcc' : '#e9d5ff', 
                      fontSize: '0.75rem', 
                      fontWeight: 'bold', 
                      textShadow: '0 0 5px #000',
                      whiteSpace: 'nowrap',
                      padding: '0 4px'
                    }}>
                      {clip.title}
                    </span>
                  </div>
                );
              })}
            
              {/* Playhead */}
              <div style={{
                position: 'absolute',
                left: `${(currentVideoTime / videoDuration) * 100}%`,
                top: 0,
                bottom: 0,
                width: '2px',
                backgroundColor: '#ff0055',
                boxShadow: '0 0 10px #ff0055',
                pointerEvents: 'none',
                zIndex: 10
              }} />
            </div>
          </div>

          <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem', flexShrink: 0 }}>
            <button className="btn-secondary" style={{ flex: 1, padding: '0.8rem', fontSize: '0.95rem', border: '1px solid rgba(0, 255, 204, 0.5)', color: '#00ffcc', fontWeight: 'bold' }} onClick={() => handleNumberChange(currentVideoTime, 'start_time')}>
               ⬅️ Set Start Here
            </button>
            <button className="btn-secondary" style={{ flex: 1, padding: '0.8rem', fontSize: '0.95rem', border: '1px solid rgba(0, 255, 204, 0.5)', color: '#00ffcc', fontWeight: 'bold' }} onClick={() => handleNumberChange(currentVideoTime, 'end_time')}>
               Set End Here ➡️
            </button>
          </div>

          <div style={{ marginTop: '0.5rem', display: 'flex', justifyContent: 'space-between', color: '#888', fontSize: '0.85rem', flexShrink: 0 }}>
            <span>Click timeline to seek. Click clip block to select.</span>
            <span>Video remains completely unedited on disk.</span>
          </div>
        </div>

        {/* RIGHT COLUMN: Clip Selector & Editor */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          
          {/* Active Clip Editor Panel */}
          {activeClip && (
            <div className="glass-panel" style={{ padding: '1.5rem', flexShrink: 0 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                <span style={{ color: '#00ffcc', fontSize: '0.8rem', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Editing Active Clip
                </span>
                <button 
                  className="btn-secondary" 
                  style={{ padding: '3px 8px', fontSize: '0.75rem', borderColor: '#ef4444', color: '#ef4444' }}
                  onClick={() => handleDeleteClip(activeClip.id)}
                  title="Delete this clip"
                >
                  🗑️ Delete
                </button>
              </div>

              <div style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', color: '#ccc', marginBottom: '0.3rem', fontSize: '0.85rem' }}>
                  Clip Title
                </label>
                <input 
                  type="text" 
                  value={activeClip.title} 
                  onChange={(e) => handleTextChange(e.target.value, 'title')}
                  style={{ width: '100%', padding: '0.6rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(0, 255, 204, 0.3)', color: '#fff', borderRadius: '8px', fontSize: '1rem', fontWeight: 'bold', boxSizing: 'border-box' }}
                />
              </div>
              
              <div style={{ marginBottom: '1.2rem' }}>
                <label style={{ display: 'block', color: '#ccc', marginBottom: '0.3rem', fontSize: '0.85rem' }}>
                  Notes / Transcript
                </label>
                <textarea 
                  rows="2"
                  value={activeClip.text} 
                  onChange={(e) => handleTextChange(e.target.value, 'text')}
                  style={{ width: '100%', padding: '0.6rem', background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', color: '#aaa', borderRadius: '8px', fontSize: '0.85rem', resize: 'vertical', boxSizing: 'border-box' }}
                />
              </div>

              <div style={{ marginBottom: '1.2rem' }}>
                <label style={{ display: 'block', color: '#ccc', marginBottom: '0.4rem', fontSize: '0.85rem' }}>
                  Start Time (seconds)
                </label>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.85rem' }} onClick={() => handleNumberChange(activeClip.start_time - 0.5, 'start_time')}>-0.5s</button>
                  <input 
                    type="number" 
                    step="0.1" 
                    min="0"
                    value={activeClip.start_time} 
                    onChange={(e) => handleNumberChange(e.target.value, 'start_time')}
                    style={{ flex: 1, minWidth: 0, padding: '0.5rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#00ffcc', borderRadius: '8px', fontSize: '0.95rem', textAlign: 'center', fontWeight: 'bold' }} 
                  />
                  <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.85rem' }} onClick={() => handleNumberChange(activeClip.start_time + 0.5, 'start_time')}>+0.5s</button>
                </div>
              </div>

              <div style={{ marginBottom: '1.5rem' }}>
                <label style={{ display: 'block', color: '#ccc', marginBottom: '0.4rem', fontSize: '0.85rem' }}>
                  End Time (seconds)
                </label>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.85rem' }} onClick={() => handleNumberChange(activeClip.end_time - 0.5, 'end_time')}>-0.5s</button>
                  <input 
                    type="number" 
                    step="0.1" 
                    min="0"
                    value={activeClip.end_time} 
                    onChange={(e) => handleNumberChange(e.target.value, 'end_time')}
                    style={{ flex: 1, minWidth: 0, padding: '0.5rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#00ffcc', borderRadius: '8px', fontSize: '0.95rem', textAlign: 'center', fontWeight: 'bold' }} 
                  />
                  <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.85rem' }} onClick={() => handleNumberChange(activeClip.end_time + 0.5, 'end_time')}>+0.5s</button>
                </div>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '1.2rem' }}>
                <span style={{ color: '#888', fontSize: '0.85rem' }}>
                  Duration: <strong style={{ color: '#fff' }}>{(activeClip.end_time - activeClip.start_time).toFixed(1)}s</strong>
                </span>
                <button className="btn-primary" onClick={() => handleExport(activeClip)} style={{ padding: '0.6rem 1.2rem' }}>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: '0.5rem', display: 'inline' }}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                  Export Clip
                </button>
              </div>
            </div>
          )}

          {/* Clips List Panel */}
          <div className="glass-panel" style={{ padding: '1.5rem', flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
              <h3 style={{ color: '#fff', margin: 0, fontSize: '1.1rem' }}>
                Clips ({clips.length})
              </h3>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button 
                  className="btn-secondary" 
                  style={{ padding: '0.4rem 0.7rem', fontSize: '0.8rem', border: '1px solid rgba(0, 255, 204, 0.4)', color: '#00ffcc' }}
                  onClick={openAddClipModal}
                >
                  + Add Clip
                </button>
                <button 
                  className="btn-primary" 
                  style={{ padding: '0.4rem 0.7rem', fontSize: '0.8rem' }}
                  onClick={handleExportAll}
                  title="Export all clips in list concurrently"
                >
                  Export All
                </button>
              </div>
            </div>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem', flex: 1, overflowY: 'auto' }}>
              {clips.map(clip => {
                const isActive = activeClipId === clip.id;
                return (
                  <div 
                    key={clip.id} 
                    onClick={() => setActiveClipId(clip.id)}
                    style={{ 
                      padding: '1rem', 
                      background: isActive ? 'rgba(0, 255, 204, 0.1)' : 'rgba(255,255,255,0.03)', 
                      border: `1px solid ${isActive ? '#00ffcc' : 'rgba(255,255,255,0.1)'}`,
                      borderRadius: '8px',
                      cursor: 'pointer',
                      transition: 'all 0.2s',
                      position: 'relative'
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
                      <strong style={{ color: isActive ? '#00ffcc' : '#eee', fontSize: '0.95rem' }}>{clip.title}</strong>
                      <span style={{ color: '#888', fontSize: '0.85rem' }}>{(clip.end_time - clip.start_time).toFixed(1)}s</span>
                    </div>
                    
                    <div style={{ color: '#aaa', fontSize: '0.85rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', marginBottom: '0.6rem' }}>
                      {clip.text}
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
                      <button 
                        className="btn-secondary"
                        style={{ padding: '2px 8px', fontSize: '0.75rem' }}
                        onClick={(e) => {
                          e.stopPropagation();
                          handleExport(clip);
                        }}
                      >
                        ⚡ Export
                      </button>
                      <button 
                        className="btn-secondary"
                        style={{ padding: '2px 6px', fontSize: '0.75rem', borderColor: 'rgba(239, 68, 68, 0.4)', color: '#ef4444' }}
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDeleteClip(clip.id);
                        }}
                      >
                        🗑️
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
          
        </div>
      </div>
    </div>
  );
}

