/**
 * EDITOR PAGE ARCHITECTURE & CONCURRENT EXPORT GUIDE
 * ==================================================
 * 
 * OVERVIEW:
 * This page is the core of the AI Clip Editor. It allows users to preview the exact 
 * mathematical crop boundaries generated by the AI without decoding video frames, 
 * and export multiple clips concurrently via an async polling architecture.
 * 
 * --------------------------------------------------
 * 
 * THE CONCURRENT EXPORT SYSTEM (Step-by-Step):
 * 
 * Problem: Video rendering via FFmpeg takes time. If we blocked the HTTP request 
 * until FFmpeg finished, the browser would timeout. Furthermore, if a user wanted 
 * to export 3 different clips at the same time, a blocking modal would ruin the UX.
 * 
 * Solution: An asynchronous polling architecture managed by React state.
 * 
 * STEP 1: Dictionary State Management
 * Instead of `const [exportJob, setExportJob]`, we use a dictionary: 
 * `const [exportJobs, setExportJobs] = useState({})`. 
 * This allows O(1) lookups and infinite concurrent jobs (e.g. { 'job1': {...}, 'job2': {...} }).
 * 
 * STEP 2: The Initial Request (handleExport)
 * When the user clicks "Export Clip":
 *   1. We instantly generate a `tempId` and push a "queued" job to the state.
 *      This immediately shows a Toast Notification to the user so they know it started.
 *   2. We send a `POST /api/v1/export/process` request containing the clip boundaries.
 *   3. The backend spins off a background thread and returns a real `export_id`.
 *   4. We swap the `tempId` in our state dictionary for the real `export_id`.
 * 
 * STEP 3: The Global Polling Effect (useEffect)
 * To avoid creating a separate `setInterval` for every single export (which could 
 * crash the browser or cause memory leaks), we use a SINGLE Global Polling Loop.
 *   1. Every 2 seconds, the loop wakes up.
 *   2. It filters the `exportJobs` dictionary for any job with status === 'processing'.
 *   3. If it finds any, it fires off parallel `fetch()` requests to `GET /status/{id}`.
 *   4. It uses a `useRef(exportJobs)` to guarantee it always reads the freshest state 
 *      inside the interval closure without needing to constantly destroy/recreate the interval.
 * 
 * STEP 4: The Floating Toast UI
 * The UI iterates over `Object.values(exportJobs)` and renders a stack of floating 
 * glassmorphism cards in the bottom-right corner. Each card independently reads its 
 * status (queued, processing, completed, error) and animates its progress bar.
 * 
 * STEP 5: The Download Trigger
 * When the polling loop sees status === 'completed', it:
 *   1. Updates the toast UI to green ("Done").
 *   2. Triggers a hidden browser download via `window.location.href = /download/{id}`.
 *   3. Sets a 5-second `setTimeout` to automatically delete the job from the dictionary, 
 *      making the toast gracefully vanish.
 */
import React, { useState, useRef, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getFullVideoUrl } from '../services/videoApi';
import mockRecipe from '../mock_recipe.json';

// Mock data to work on the UI without relying on the backend
const MOCK_CLIPS = [
  { id: 'clip_1', start_time: 15.0, end_time: 45.0, text: "This is the most incredible thing I've ever seen...", title: "Viral Hook 1" },
  { id: 'clip_2', start_time: 60.5, end_time: 90.0, text: "If you want to succeed, you have to stop doing this.", title: "Advice Segment" },
  { id: 'clip_3', start_time: 120.0, end_time: 155.0, text: "And that's why the market is crashing right now.", title: "Market Analysis" }
];

export default function EditorPage() {
  const { savedFilename } = useParams();
  const navigate = useNavigate();
  const videoRef = useRef(null);
  
  const [activeClipId, setActiveClipId] = useState(MOCK_CLIPS[0].id);
  const [clips, setClips] = useState(MOCK_CLIPS);
  
  const activeClip = clips.find(c => c.id === activeClipId);

  // Timeline Drag-to-Scroll State
  const timelineRef = useRef(null);
  const [isDragging, setIsDragging] = useState(false);
  const [startX, setStartX] = useState(0);
  const [scrollLeft, setScrollLeft] = useState(0);
  const [hasDragged, setHasDragged] = useState(false);

  // For the Zero-CPU Preview overlay box
  const [boxPosition, setBoxPosition] = useState({ x: 50, y: 50 }); // percentage
  const [trackingData, setTrackingData] = useState([]);
  const [videoWidth, setVideoWidth] = useState(1920);
  const [videoHeight, setVideoHeight] = useState(1080);
  const [videoDuration, setVideoDuration] = useState(300);
  const [currentVideoTime, setCurrentVideoTime] = useState(0);

  // Export State (Dictionary to support multiple concurrent exports)
  const [exportJobs, setExportJobs] = useState({});
  const exportJobsRef = useRef(exportJobs);
  
  // Keep ref in sync for the interval
  useEffect(() => {
    exportJobsRef.current = exportJobs;
  }, [exportJobs]);

  // Load the real AI tracking data directly from the generated recipe file
  useEffect(() => {
    if (mockRecipe && mockRecipe.global_tracking) {
      setTrackingData(mockRecipe.global_tracking);
    }
  }, []);

  // Global Polling Effect for all active Export Jobs
  useEffect(() => {
    const intervalId = setInterval(async () => {
      const currentJobs = exportJobsRef.current;
      const processingJobs = Object.values(currentJobs).filter(j => j.status === 'processing');
      
      if (processingJobs.length === 0) return;
      
      for (const job of processingJobs) {
        if (job.id.startsWith('temp_')) continue;
        
        try {
          const res = await fetch(`http://localhost:8000/api/v1/export/status/${job.id}`);
          const data = await res.json();
          
          if (data.status === 'completed') {
            setExportJobs(prev => ({ ...prev, [job.id]: { ...prev[job.id], status: 'completed' } }));
            // Trigger actual file download
            window.location.href = `http://localhost:8000/api/v1/export/download/${job.id}`;
            
            // Auto remove toast after 5 seconds
            setTimeout(() => {
              setExportJobs(prev => {
                const newJobs = { ...prev };
                delete newJobs[job.id];
                return newJobs;
              });
            }, 5000);
          } else if (data.status === 'error') {
            setExportJobs(prev => ({ ...prev, [job.id]: { ...prev[job.id], status: 'error', error: data.error_detail } }));
          } else if (data.status === 'cancelled') {
            setExportJobs(prev => ({ ...prev, [job.id]: { ...prev[job.id], status: 'cancelled' } }));
          }
        } catch (e) {
          console.error(`Polling error for ${job.id}`, e);
        }
      }
    }, 2000);
    
    return () => clearInterval(intervalId);
  }, []);

  const handleTimelineMouseDown = (e) => {
    setIsDragging(true);
    setHasDragged(false);
    setStartX(e.pageX - timelineRef.current.offsetLeft);
    setScrollLeft(timelineRef.current.scrollLeft);
  };

  const handleTimelineMouseMove = (e) => {
    if (!isDragging) return;
    e.preventDefault();
    const x = e.pageX - timelineRef.current.offsetLeft;
    const walk = (x - startX) * 1.5; // Scroll speed multiplier
    if (Math.abs(walk) > 5) setHasDragged(true); // Treat as a drag, not a click
    timelineRef.current.scrollLeft = scrollLeft - walk;
  };

  const handleTimelineClick = (e, videoDur) => {
    if (hasDragged) return; // Prevent seeking if the user was just trying to scroll
    const rect = e.currentTarget.getBoundingClientRect();
    const percentage = (e.clientX - rect.left) / rect.width;
    if (videoRef.current) videoRef.current.currentTime = Math.max(0, Math.min(videoDur, percentage * videoDur));
  };

  const handleTimeUpdate = () => {
    if (!videoRef.current) return;
    const currentTime = videoRef.current.currentTime;
    setCurrentVideoTime(currentTime);
    
    if (trackingData.length === 0) return;
    
    // Find the active tracking block for this timestamp
    const currentBlock = trackingData.find(b => currentTime >= b.start_time_seconds && currentTime <= b.end_time_seconds);
    
    if (currentBlock) {
      if (currentBlock.crop_x !== undefined) {
        // Option 1: Backend provides exact FFmpeg crop coordinates (Source of Truth)
        let pX = (currentBlock.crop_x / videoWidth) * 100;
        let pY = (currentBlock.crop_y / videoHeight) * 100;
        setBoxPosition({ x: pX, y: pY });
      } else {
        // Option 2: Legacy fallback. Calculate the clamp math identically to how FFmpeg would do it.
        const crop_width = videoHeight * (9/16);
        const target_x = currentBlock.center_x_coordinate - (crop_width / 2);
        const clamped_x = Math.max(0, Math.min(videoWidth - crop_width, target_x));
        
        let pX = (clamped_x / videoWidth) * 100;
        setBoxPosition({ x: pX, y: 0 });
      }
    }
  };

  const handleLoadedMetadata = () => {
    if (videoRef.current) {
      setVideoDuration(videoRef.current.duration);
      if (videoRef.current.videoWidth) setVideoWidth(videoRef.current.videoWidth);
      if (videoRef.current.videoHeight) setVideoHeight(videoRef.current.videoHeight);
    }
  };

  const handleNumberChange = (val, field) => {
    let num = parseFloat(val);
    if (isNaN(num)) num = 0;
    setClips(clips.map(c => c.id === activeClipId ? { ...c, [field]: num } : c));
    
    // Seek video to the new time so user can preview their cut
    if (videoRef.current) {
      videoRef.current.currentTime = num;
    }
  };

  const handleExport = async (clipToExport) => {
    const tempId = `temp_${Date.now()}`;
    
    setExportJobs(prev => ({
      ...prev,
      [tempId]: { id: tempId, title: clipToExport.title, status: 'queued', isExporting: true }
    }));
    
    try {
      const payload = {
        saved_filename: savedFilename || 'demo.mp4',
        start_time: clipToExport.start_time,
        end_time: clipToExport.end_time,
        tracking_data: trackingData
      };

      const response = await fetch('http://localhost:8000/api/v1/export/process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      
      const data = await response.json();
      
      if (!response.ok) {
        throw new Error(data.detail || "Failed to start export");
      }
      
      if (data.status === 'already_running') {
        // Swap temp ID for the real ID that is already running
        setExportJobs(prev => {
          const newJobs = { ...prev };
          delete newJobs[tempId];
          newJobs[data.export_id] = { id: data.export_id, title: clipToExport.title, status: 'processing', isExporting: true };
          return newJobs;
        });
        return;
      }

      // Set the real export ID to start the polling effect
      setExportJobs(prev => {
        const newJobs = { ...prev };
        delete newJobs[tempId];
        newJobs[data.export_id] = { id: data.export_id, title: clipToExport.title, status: 'processing', isExporting: true };
        return newJobs;
      });
      
    } catch (error) {
      setExportJobs(prev => ({
        ...prev,
        [tempId]: { ...prev[tempId], status: 'error', error: error.message }
      }));
    }
  };

  const handleCancelExport = async (exportId) => {
    // If it's still a temporary ID, it hasn't even reached the server yet. Just remove it locally.
    if (exportId.startsWith('temp_')) {
      setExportJobs(prev => {
        const newJobs = { ...prev };
        delete newJobs[exportId];
        return newJobs;
      });
      return;
    }
    
    // Optimistically mark as cancelling
    setExportJobs(prev => ({ ...prev, [exportId]: { ...prev[exportId], status: 'cancelling' } }));
    
    try {
      await fetch(`http://localhost:8000/api/v1/export/cancel/${exportId}`, { method: 'POST' });
      // The polling loop will catch the 'cancelled' status on the next tick
    } catch (err) {
      console.error("Failed to cancel export", err);
      alert("Failed to cancel export job.");
    }
  };

  return (
    <div className="editor-page-root" style={{ padding: '2rem 3rem', minHeight: 'calc(100vh - 80px)', display: 'flex', flexDirection: 'column', boxSizing: 'border-box' }}>
      
      {/* Floating Export Toast Notifications */}
      {Object.keys(exportJobs).length > 0 && (
        <div style={{
          position: 'fixed',
          bottom: '20px',
          right: '20px',
          display: 'flex',
          flexDirection: 'column',
          gap: '10px',
          zIndex: 9999,
          maxWidth: '350px'
        }}>
          {Object.values(exportJobs).map(job => (
            <div key={job.id} className="glass-panel" style={{ padding: '1.2rem', display: 'flex', flexDirection: 'column', gap: '8px', border: `1px solid ${job.status === 'completed' ? '#10b981' : job.status === 'error' || job.status === 'cancelled' ? '#ef4444' : '#00ffcc'}`, borderLeftWidth: '4px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <strong style={{ color: '#fff', fontSize: '0.9rem' }}>{job.title}</strong>
                <span style={{ fontSize: '0.8rem', color: job.status === 'completed' ? '#10b981' : job.status === 'error' || job.status === 'cancelled' ? '#ef4444' : '#00ffcc' }}>
                  {job.status === 'completed' ? 'Done' : job.status === 'error' ? 'Failed' : job.status === 'cancelled' ? 'Cancelled' : job.status === 'cancelling' ? 'Cancelling...' : 'Exporting...'}
                </span>
              </div>
              
              {job.status === 'error' && (
                <div style={{ color: '#ef4444', fontSize: '0.8rem' }}>{job.error}</div>
              )}
              
              {(job.status === 'queued' || job.status === 'processing' || job.status === 'cancelling') && (
                <div style={{ width: '100%', height: '4px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', overflow: 'hidden' }}>
                  <div style={{ 
                    width: job.status === 'processing' ? '70%' : '20%', 
                    height: '100%', 
                    background: '#00ffcc', 
                    transition: 'width 0.5s ease',
                    animation: job.status === 'processing' ? 'pulse 2s infinite' : 'none' 
                  }} />
                </div>
              )}
              
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: '4px' }}>
                {(job.status === 'queued' || job.status === 'processing') && (
                  <button className="btn-secondary" style={{ padding: '4px 8px', fontSize: '0.8rem', border: '1px solid #ef4444', color: '#ef4444' }} onClick={() => handleCancelExport(job.id)}>
                    Cancel
                  </button>
                )}
                
                {(job.status === 'error' || job.status === 'completed' || job.status === 'cancelled') && (
                  <button className="btn-secondary" style={{ padding: '4px 8px', fontSize: '0.8rem' }} onClick={() => {
                    setExportJobs(prev => {
                      const newJobs = { ...prev };
                      delete newJobs[job.id];
                      return newJobs;
                    });
                  }}>Dismiss</button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h2>Interactive Clip Editor <span style={{ color: '#00ffcc' }}>🎬</span></h2>
        <button className="btn-secondary" onClick={() => navigate('/')}>
          ⬅️ Back to Pipeline
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 350px', gap: '2rem', flex: 1, minHeight: 0 }}>
        
        {/* LEFT COLUMN: Zero-CPU Preview Player */}
        <div className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', minHeight: 0, minWidth: 0 }}>
          <h3 style={{ color: '#00ffcc', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect></svg>
            Zero-CPU Tracking Preview
          </h3>
          
          <div style={{ position: 'relative', width: '100%', backgroundColor: '#050505', borderRadius: '12px', overflow: 'hidden', display: 'inline-block' }}>
            <video 
              ref={videoRef}
              src={getFullVideoUrl(`/storage/uploads/${savedFilename}`)}
              controls
              onTimeUpdate={handleTimeUpdate}
              onLoadedMetadata={handleLoadedMetadata}
              style={{ width: '100%', maxHeight: '60vh', display: 'block' }}
            />
            
            {/* The 9:16 tracking overlay box */}
            <div style={{
              position: 'absolute',
              top: 0,
              height: '100%',
              aspectRatio: '9 / 16',
              border: '3px solid #00ffcc',
              boxShadow: '0 0 0 9999px rgba(0,0,0,0.6), inset 0 0 15px rgba(0, 255, 204, 0.3)',
              left: `${boxPosition.x}%`,
              top: `${boxPosition.y}%`,
              pointerEvents: 'none',
              display: 'flex',
              flexDirection: 'column',
              padding: '10px'
            }}>
              <div style={{ background: 'rgba(0, 255, 204, 0.9)', color: '#000', fontSize: '0.7rem', padding: '2px 8px', borderRadius: '4px', alignSelf: 'flex-start', fontWeight: 'bold' }}>
                9:16 CROP AREA
              </div>
            </div>
          </div>
          
          {/* Scrollable Visual Timeline Bar */}
          <div 
            ref={timelineRef}
            className="custom-scrollbar" 
            style={{ 
              marginTop: '1.5rem', 
              width: '100%', 
              overflowX: 'auto', 
              borderRadius: '8px', 
              border: '1px solid rgba(255,255,255,0.1)', 
              background: 'rgba(0,0,0,0.5)', 
              paddingBottom: '4px',
              cursor: isDragging ? 'grabbing' : 'grab' 
            }}
            onMouseDown={handleTimelineMouseDown}
            onMouseMove={handleTimelineMouseMove}
            onMouseUp={() => setIsDragging(false)}
            onMouseLeave={() => setIsDragging(false)}
          >
            <div 
              style={{ width: `${Math.max(100, videoDuration * 4)}px`, minWidth: '100%', height: '50px', position: 'relative', flexShrink: 0 }}
              onClick={(e) => handleTimelineClick(e, videoDuration)}
            >
            {/* The active clip highlighted region */}
            <div style={{
              position: 'absolute',
              left: `${(activeClip.start_time / videoDuration) * 100}%`,
              width: `${((activeClip.end_time - activeClip.start_time) / videoDuration) * 100}%`,
              height: '100%',
              background: 'rgba(0, 255, 204, 0.3)',
              borderLeft: '2px solid #00ffcc',
              borderRight: '2px solid #00ffcc',
              pointerEvents: 'none',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}>
              <span style={{ color: '#00ffcc', fontSize: '0.8rem', fontWeight: 'bold', textShadow: '0 0 5px #000' }}>Active Clip</span>
            </div>
            
              {/* Playhead */}
              <div style={{
                position: 'absolute',
                left: `${(currentVideoTime / videoDuration) * 100}%`,
                top: 0,
                bottom: 0,
                width: '2px',
                backgroundColor: '#ff0055',
                boxShadow: '0 0 10px #ff0055',
                pointerEvents: 'none',
                zIndex: 10
              }} />
            </div>
          </div>

          <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem', flexShrink: 0 }}>
            <button className="btn-secondary" style={{ flex: 1, padding: '0.8rem', fontSize: '1rem', border: '1px solid rgba(0, 255, 204, 0.5)', color: '#00ffcc', fontWeight: 'bold' }} onClick={() => handleNumberChange(currentVideoTime, 'start_time')}>
               ⬅️ Set Start Here
            </button>
            <button className="btn-secondary" style={{ flex: 1, padding: '0.8rem', fontSize: '1rem', border: '1px solid rgba(0, 255, 204, 0.5)', color: '#00ffcc', fontWeight: 'bold' }} onClick={() => handleNumberChange(currentVideoTime, 'end_time')}>
               Set End Here ➡️
            </button>
          </div>

          <div style={{ marginTop: '0.5rem', display: 'flex', justifyContent: 'space-between', color: '#888', fontSize: '0.9rem', flexShrink: 0 }}>
            <span>Click timeline to jump. Use buttons to lock bounds.</span>
            <span>Video remains completely unedited on disk.</span>
          </div>
        </div>

        {/* RIGHT COLUMN: Clip Selector & Editor */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          
          {/* Active Clip Editor Panel */}
          <div className="glass-panel" style={{ padding: '1.5rem', flexShrink: 0 }}>
            <h3 style={{ color: '#fff', marginBottom: '1rem' }}>Editing: <span style={{ color: '#00ffcc' }}>{activeClip.title}</span></h3>
            
            <p style={{ color: '#aaa', fontSize: '0.95rem', fontStyle: 'italic', marginBottom: '1.5rem', background: 'rgba(0,0,0,0.3)', padding: '1rem', borderRadius: '8px' }}>
              "{activeClip.text}"
            </p>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', color: '#ccc', marginBottom: '0.5rem' }}>
                Start Time (seconds)
              </label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.9rem' }} onClick={() => handleNumberChange(activeClip.start_time - 0.5, 'start_time')}>-0.5s</button>
                <input 
                  type="number" 
                  step="0.1" 
                  min="0"
                  value={activeClip.start_time} 
                  onChange={(e) => handleNumberChange(e.target.value, 'start_time')}
                  style={{ flex: 1, minWidth: 0, padding: '0.6rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#00ffcc', borderRadius: '8px', fontSize: '1rem', textAlign: 'center', fontWeight: 'bold' }} 
                />
                <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.9rem' }} onClick={() => handleNumberChange(activeClip.start_time + 0.5, 'start_time')}>+0.5s</button>
              </div>
            </div>

            <div style={{ marginBottom: '2rem' }}>
              <label style={{ display: 'block', color: '#ccc', marginBottom: '0.5rem' }}>
                End Time (seconds)
              </label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.9rem' }} onClick={() => handleNumberChange(activeClip.end_time - 0.5, 'end_time')}>-0.5s</button>
                <input 
                  type="number" 
                  step="0.1" 
                  min="0"
                  value={activeClip.end_time} 
                  onChange={(e) => handleNumberChange(e.target.value, 'end_time')}
                  style={{ flex: 1, minWidth: 0, padding: '0.6rem', background: 'rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.2)', color: '#00ffcc', borderRadius: '8px', fontSize: '1rem', textAlign: 'center', fontWeight: 'bold' }} 
                />
                <button className="btn-secondary" style={{ padding: '0.5rem', flexShrink: 0, fontSize: '0.9rem' }} onClick={() => handleNumberChange(activeClip.end_time + 0.5, 'end_time')}>+0.5s</button>
              </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '1.5rem' }}>
              <span style={{ color: '#888' }}>
                Duration: <strong>{(activeClip.end_time - activeClip.start_time).toFixed(1)}s</strong>
              </span>
              <button className="btn-primary" onClick={() => handleExport(activeClip)} style={{ padding: '0.6rem 1.2rem' }}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: '0.5rem', display: 'inline' }}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                Export Clip
              </button>
            </div>
          </div>

          {/* Clips List */}
          <div className="glass-panel" style={{ padding: '1.5rem', flex: 1, overflowY: 'auto' }}>
            <h3 style={{ color: '#fff', marginBottom: '1rem', fontSize: '1.1rem' }}>Generated Clips</h3>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
              {clips.map(clip => (
                <div 
                  key={clip.id} 
                  onClick={() => setActiveClipId(clip.id)}
                  style={{ 
                    padding: '1rem', 
                    background: activeClipId === clip.id ? 'rgba(0, 255, 204, 0.1)' : 'rgba(255,255,255,0.03)', 
                    border: `1px solid ${activeClipId === clip.id ? '#00ffcc' : 'rgba(255,255,255,0.1)'}`,
                    borderRadius: '8px',
                    cursor: 'pointer',
                    transition: 'all 0.2s'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                    <strong style={{ color: activeClipId === clip.id ? '#00ffcc' : '#eee' }}>{clip.title}</strong>
                    <span style={{ color: '#888', fontSize: '0.85rem' }}>{(clip.end_time - clip.start_time).toFixed(1)}s</span>
                  </div>
                  <div style={{ color: '#aaa', fontSize: '0.85rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {clip.text}
                  </div>
                </div>
              ))}
            </div>
          </div>
          
        </div>
      </div>
    </div>
  );
}
